### PR TITLE
Node 12 fixes

### PR DESCRIPTION
**Pull request by jimmythesaint82**
All node 12 fixes

### CODE REVIEW

**Comment by Stunc0** [comment]
Does this package is still maintain ? Cause i see that this pull request is there since many months ...

**Comment by gjrdiesel** [comment]
For anyone on node12 you can install this PR w/ this command:
```
npm install pokusew/node-pcsclite#pull/26/head
````

**Comment by Stunc0** [comment]
> npm install pokusew/node-pcsclite#pull/26/head

I still have many issues during the npm install with this one. Because i need to "node-gyp rebuild"...
And during the rebuild i have a lot of warning
TinyGrab Screen Shot 20-09-2019 10 53 08

**Comment by jorispz** [comment]
I've installed from this branch successfully on raspbian, thanks @jimmythesaint82 

@pokusew any change of this getting merged for a proper release?

**Comment by janhon3n** [comment]
I've managed to get it working with electron 6.1.7, but with version 7 the electron-rebuild fails with similar interface errors.  The node version is upgraded in the release from 12.4.0 to 12.8.1 . Any ideas how to fix?

**Comment by Stunc0** [comment]
I'm not using this one anymore but with the original pcsclite 1.0.0. And it works actually with electron 7.1.7 and node 12.14.1. Have you tried an npm rebuild ?

**Comment by pokusew** [comment]
Hi @jimmythesaint82,

Thank you very much for your PR. **I really appreciate the work you did.** 👍

I am really sorry it look me so long to review and merge it.

However, during the last months, **more breaking changes** in the Node.js and especially in the nan wrapper methods **emerged**, so **the changes in this PR are longer sufficient in the newest Node.js 12** (and 13).

Now I am working with @petrzjunior to prepare a series of follow-up changes (#27) that should make this package fully compatible with Node.js 12 and 13 and also replace legacy nan usages with the current best practices. I expect **a new release containing these fixes** and improvements **in about a week**.

Thanks again for your contributions. 🙂 

cc @Stunc0, @gjrdiesel, @jorispz, @janhon3n

**Pull request merged**
